/**
 * `selora completion [bash|zsh|fish]` — prints a shell completion script to
 * stdout. The script is GENERATED from the live commander program passed in
 * by buildProgram(): every command name, description, and option (including
 * the global --debug/--json/--api-url) is walked from that instance, so the
 * completion can never drift from the registered commands — a new command
 * appears in the scripts automatically, and a completion test fails loudly if
 * the walk misses anything.
 *
 * The three scripts are original and minimal: they complete commands and
 * flags (plus the `keys` sub-actions); they do not attempt argument-value
 * completion. With no shell argument, the target defaults from the basename
 * of $SHELL when it is bash/zsh/fish; otherwise the command prints usage.
 */

import type { Command } from 'commander';
import type { CliContext } from '../context.js';
import { Renderer } from '../terminal/render.js';

export const SUPPORTED_SHELLS = ['bash', 'zsh', 'fish'] as const;
export type Shell = (typeof SUPPORTED_SHELLS)[number];

/**
 * Positional vocabularies for commands whose first argument is one of a fixed
 * set of words. This is command vocabulary, not a command list — commands
 * themselves always come from the live program.
 */
const POSITIONAL_WORDS: Record<string, string[]> = {
  keys: ['list', 'create', 'revoke'],
};

interface OptionSpec {
  /** Flag tokens as typed by the user, e.g. ['-V', '--version'] or ['--debug']. */
  tokens: string[];
  description: string;
  /** 'required' (`--api-url <url>`), 'optional' (`--key [value]`), or 'none'. */
  valueMode: 'none' | 'required' | 'optional';
}

interface CommandSpec {
  name: string;
  description: string;
  options: OptionSpec[];
  positionalWords: string[];
}

function commandSpec(cmd: Command): CommandSpec {
  const options: OptionSpec[] = cmd.options.map((o) => {
    const tokens: string[] = [];
    if (o.short !== undefined && o.short !== '') tokens.push(o.short);
    if (o.long !== undefined && o.long !== '') tokens.push(o.long);
    if (tokens.length === 0) {
      // Defensive: an option without parsed short/long — fall back to flags.
      for (const tok of o.flags.split(/[\s,]+/)) {
        if (tok.startsWith('-')) tokens.push(tok);
      }
    }
    // '--api-url <url>' requires a value; '--key [value]' accepts one.
    const valueMode: OptionSpec['valueMode'] = /<[^\s>]+>/.test(o.flags)
      ? 'required'
      : /\[[^\]]+\]/.test(o.flags)
        ? 'optional'
        : 'none';
    return { tokens, description: o.description ?? '', valueMode };
  });
  // commander registers -h/--help lazily at parse time, so it is not in
  // cmd.options yet — every command has it, so add it explicitly.
  if (!options.some((o) => o.tokens.includes('--help'))) {
    options.push({
      tokens: ['-h', '--help'],
      description: 'display help for command',
      valueMode: 'none',
    });
  }
  return {
    name: cmd.name(),
    description: cmd.description() ?? '',
    options,
    positionalWords: POSITIONAL_WORDS[cmd.name()] ?? [],
  };
}

/** The root program's own options (version/help + the globals). */
function rootSpec(program: Command): CommandSpec {
  return commandSpec(program);
}

function subcommands(program: Command): CommandSpec[] {
  return program.commands.map((c) => commandSpec(c));
}

// ---------------------------------------------------------------------------
// Escaping — the generated scripts must stay valid shell regardless of what
// the descriptions contain.

function escSingleQuoted(s: string): string {
  return s.replace(/(['\\])/g, '\\$1');
}

/** zsh _describe specs use name[description] — no bare brackets in the text. */
function plainDescription(s: string): string {
  return s.replace(/[[\]]/g, ' ');
}

// ---------------------------------------------------------------------------
// bash

export function generateBashCompletion(program: Command): string {
  const root = rootSpec(program);
  const cmds = subcommands(program);
  const lines: string[] = [
    '# selora bash completion — generated by `selora completion bash`.',
    '# Load it in the current shell:  eval "$(selora completion bash)"',
    '',
    `_selora_commands="${cmds.map((c) => c.name).join(' ')}"`,
    `_selora_root_opts="${root.options.flatMap((o) => o.tokens).join(' ')}"`,
  ];
  for (const c of cmds) {
    const words = [...c.positionalWords, ...c.options.flatMap((o) => o.tokens)].join(' ');
    lines.push(`_selora_opts_${c.name}="${words}"`);
  }
  // Options that take a value: nothing sensible to complete after them.
  const valueOpts = [
    ...new Set(
      [root, ...cmds]
        .flatMap((c) => c.options.filter((o) => o.valueMode !== 'none'))
        .flatMap((o) => o.tokens)
        .filter((t) => t.startsWith('--')),
    ),
  ];
  lines.push(
    '_selora()',
    '{',
    '  local cur prev cmd i',
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '  cmd=""',
    '  # find the subcommand: first non-option word after the program name',
    '  for ((i=1; i<COMP_CWORD; i++)); do',
    '    case "${COMP_WORDS[i]}" in',
    '      -*) ;;',
    '      *) if [ -z "$cmd" ]; then cmd="${COMP_WORDS[i]}"; fi ;;',
    '    esac',
    '  done',
  );
  // after a value-taking option there is nothing to complete. The alternation
  // is inlined (case patterns resolve `|` at parse time, not from variables).
  if (valueOpts.length > 0) {
    lines.push('  case "$prev" in', `    ${valueOpts.join('|')}) return 0 ;;`, '  esac');
  }
  lines.push(
    '  if [ -n "$cmd" ]; then',
    '    local var="_selora_opts_${cmd}"',
    '    local opts="${!var:-}"',
    '    COMPREPLY=( $(compgen -W "${opts} ${_selora_root_opts}" -- "$cur") )',
    '  else',
    '    COMPREPLY=( $(compgen -W "${_selora_commands} ${_selora_root_opts}" -- "$cur") )',
    '  fi',
    '  return 0',
    '}',
    'complete -F _selora selora',
  );
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// zsh

export function generateZshCompletion(program: Command): string {
  const root = rootSpec(program);
  const cmds = subcommands(program);
  const lines: string[] = [
    '#compdef selora',
    '# selora zsh completion — generated by `selora completion zsh`.',
    '# Source it from your .zshrc, or drop it on your fpath as a file named _selora.',
    '',
    '_selora() {',
    '  local -a cmds',
    '  cmds=(',
  ];
  for (const c of cmds) {
    lines.push(
      `    '${escSingleQuoted(c.name)}:${escSingleQuoted(plainDescription(c.description))}'`,
    );
  }
  lines.push(
    '  )',
    '  if (( CURRENT == 2 )); then',
    "    _describe -t commands 'selora command' cmds",
    '    return 0',
    '  fi',
    '  local cmd="${words[2]}"',
    '  local -a opts',
    '  opts=(',
  );
  const zshSpec = (t: string, d: string): string =>
    `'${escSingleQuoted(t)}[${escSingleQuoted(plainDescription(d))}]'`;
  for (const o of root.options) {
    for (const t of o.tokens) lines.push(`    ${zshSpec(t, o.description)}`);
  }
  lines.push('  )');
  // One case statement; every branch adds the command's own options.
  const branches = cmds.filter((c) => c.options.length > 0 || c.positionalWords.length > 0);
  if (branches.length > 0) {
    lines.push('  case "$cmd" in');
    for (const c of branches) {
      lines.push(`    ${c.name})`);
      for (const o of c.options) {
        for (const t of o.tokens) {
          lines.push(`      opts+=(${zshSpec(t, o.description)})`);
        }
      }
      if (c.positionalWords.length > 0) {
        lines.push(
          '      if (( CURRENT == 3 )); then',
          '        local -a actions',
          `        actions=(${c.positionalWords.map((w) => `'${w}'`).join(' ')})`,
          "        _describe -t actions 'argument' actions",
          '        return 0',
          '      fi',
        );
      }
      lines.push('      ;;');
    }
    lines.push('  esac');
  }
  lines.push("  _describe -t options 'option' opts", '  return 0', '}', '', '_selora "$@"');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// fish

export function generateFishCompletion(program: Command): string {
  const root = rootSpec(program);
  const cmds = subcommands(program);
  const lines: string[] = [
    '# selora fish completion — generated by `selora completion fish`.',
    '# Save it to a file in ~/.config/fish/completions/ (e.g. selora.fish), or run:',
    '#   selora completion fish > ~/.config/fish/completions/selora.fish',
    '',
  ];
  const desc = (d: string): string => ` -d '${escSingleQuoted(plainDescription(d))}'`;
  const emitOption = (cond: string, o: OptionSpec): void => {
    let s = `complete -c selora -n "${cond}"`;
    for (const t of o.tokens) {
      if (t.startsWith('--')) s += ` -l ${t.slice(2)}`;
      else s += ` -s ${t.replace(/^-/, '')}`;
    }
    if (o.valueMode === 'required') s += ' -x'; // requires a value, no file completion
    s += desc(o.description);
    lines.push(s);
  };
  // Root options complete everywhere (root and after any subcommand).
  const anyCmd =
    cmds.length > 0
      ? `__fish_use_subcommand; or __fish_seen_subcommand_from ${cmds.map((c) => c.name).join(' ')}`
      : '__fish_use_subcommand';
  for (const o of root.options) emitOption(anyCmd, o);
  lines.push('');
  for (const c of cmds) {
    lines.push(
      `complete -c selora -n '__fish_use_subcommand' -a '${escSingleQuoted(c.name)}'${desc(c.description)}`,
    );
  }
  lines.push('');
  for (const c of cmds) {
    const cond = `__fish_seen_subcommand_from ${escSingleQuoted(c.name)}`;
    for (const o of c.options) emitOption(cond, o);
    if (c.positionalWords.length > 0) {
      // Only while no positional word has been typed yet (commandline -opc
      // lists the command line up to the cursor, minus the current token).
      lines.push(
        `complete -c selora -n "${cond}; and test (count (commandline -opc)) -eq 2" -a '${c.positionalWords.join(' ')}'`,
      );
    }
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// The command.

/** Bash/zsh/fish from the basename of $SHELL; undefined otherwise. */
export function shellFromEnv(env: NodeJS.ProcessEnv = process.env): Shell | undefined {
  const raw = env['SHELL'];
  if (typeof raw !== 'string' || raw === '') return undefined;
  const base = raw.slice(raw.lastIndexOf('/') + 1);
  return SUPPORTED_SHELLS.find((s) => s === base);
}

export function shellScript(shell: Shell, program: Command): string {
  if (shell === 'bash') return generateBashCompletion(program);
  if (shell === 'zsh') return generateZshCompletion(program);
  return generateFishCompletion(program);
}

export async function runCompletion(
  ctx: CliContext,
  shellArg: string | undefined,
  program: Command,
): Promise<void> {
  const r = new Renderer({ out: ctx.io.out, err: ctx.io.err, json: ctx.json, debug: ctx.debug });

  let shell: Shell | undefined;
  if (shellArg !== undefined) {
    const found = SUPPORTED_SHELLS.find((s) => s === shellArg.trim().toLowerCase());
    if (found === undefined) {
      r.fail(`Unknown shell: ${shellArg} — expected bash, zsh, or fish.`);
      process.exitCode = 1;
      return;
    }
    shell = found;
  } else {
    shell = shellFromEnv();
  }

  if (shell === undefined) {
    r.fail('Usage: selora completion <bash|zsh|fish>');
    r.bullet('Prints a completion script for the given shell to stdout.');
    r.bullet('bash:  eval "$(selora completion bash)"');
    r.bullet('zsh:   source it from .zshrc, or drop it on your fpath as _selora');
    r.bullet('fish:  selora completion fish > ~/.config/fish/completions/selora.fish');
    process.exitCode = 1;
    return;
  }

  const script = shellScript(shell, program);
  if (ctx.json) {
    r.jsonOut({ ok: true, shell, script });
    return;
  }
  ctx.io.out(script);
}
